#spring.application.name=RestApiSample

spring:
  application:
    name: RestApiSample
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_spring_boot?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
  jackson:
      property-naming-strategy: SNAKE_CASE
